import Product from "./models/productModel.js";
import mongoose from "mongoose";
import dotenv from "dotenv";
dotenv.config();
const seedDB = async () => {
    try {
        await mongoose.connect(process.env.MONGOOSE_URL);
        console.log("Mongoose Connected");

        await Product.deleteMany({});
        console.log("Existing Products deleted");

        const products = [
            // ==========================================
            // FRUITS & VEGETABLES (25 Items)
            // ==========================================
            {
                "name": "Blueberries 125g",
                "description": "Sweet, juicy, and packed with antioxidants.",
                "price": 180,
                "originalPrice": 200,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/blueberries_fresh_125.png",
                "category": "fruits-vegetables",
                "unit": "125g",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.8,
                "reviewCount": 34
            },
            {
                "name": "Strawberries 250g",
                "description": "Vibrant red, sweet berries perfect for desserts.",
                "price": 120,
                "originalPrice": 140,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/strawberries_pack_250.png",
                "category": "fruits-vegetables",
                "unit": "250g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 28
            },
            {
                "name": "Avocado 2 pcs",
                "description": "Creamy texture, rich in healthy monounsaturated fats.",
                "price": 220,
                "originalPrice": 250,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/avocado_hass_twin.png",
                "category": "fruits-vegetables",
                "unit": "2pcs",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.6,
                "reviewCount": 19
            },
            {
                "name": "Broccoli 500g",
                "description": "Crisp green florets high in Vitamin C and K.",
                "price": 75,
                "originalPrice": 90,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/broccoli_heads_500.png",
                "category": "fruits-vegetables",
                "unit": "500g",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.5,
                "reviewCount": 15
            },
            {
                "name": "Red Bell Pepper 500g",
                "description": "Sweet, crunchy peppers ideal for stir-fries and salads.",
                "price": 95,
                "originalPrice": 110,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/bell_pepper_red.png",
                "category": "fruits-vegetables",
                "unit": "500g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 22
            },
            {
                "name": "Yellow Bell Pepper 500g",
                "description": "Bright and mild pepper variety packed with nutrition.",
                "price": 95,
                "originalPrice": 110,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/bell_pepper_yellow.png",
                "category": "fruits-vegetables",
                "unit": "500g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.2,
                "reviewCount": 14
            },
            {
                "name": "English Cucumber 500g",
                "description": "Seedless, thin-skinned cucumber with a crisp bite.",
                "price": 40,
                "originalPrice": 45,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cucumber_english_500.png",
                "category": "fruits-vegetables",
                "unit": "500g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 31
            },
            {
                "name": "Lemon 250g",
                "description": "Zesty, tart citrus perfect for garnishes and dressings.",
                "price": 30,
                "originalPrice": 35,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/lemons_yellow_sour.png",
                "category": "fruits-vegetables",
                "unit": "250g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 42
            },
            {
                "name": "Garlic 250g",
                "description": "Pungent and aromatic bulbs essential for savory cooking.",
                "price": 60,
                "originalPrice": 70,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/garlic_bulbs_fresh.png",
                "category": "fruits-vegetables",
                "unit": "250g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 27
            },
            {
                "name": "Ginger 250g",
                "description": "Spicy, earthy root ideal for teas and culinary bases.",
                "price": 45,
                "originalPrice": 50,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/ginger_root_spicy.png",
                "category": "fruits-vegetables",
                "unit": "250g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 18
            },
            {
                "name": "Cauliflower 1 pc",
                "description": "Firm white head, versatile vegetable for roasting or mashing.",
                "price": 40,
                "originalPrice": 50,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cauliflower_head_single.png",
                "category": "fruits-vegetables",
                "unit": "1pc",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.1,
                "reviewCount": 23
            },
            {
                "name": "Green Chili 100g",
                "description": "Sharp, spicy chilies to add heat to any recipe.",
                "price": 15,
                "originalPrice": 18,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/green_chili_hot.png",
                "category": "fruits-vegetables",
                "unit": "100g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 39
            },
            {
                "name": "Coriander Leaves 100g",
                "description": "Fresh aromatic herb ideal for garnishing and chutneys.",
                "price": 12,
                "originalPrice": 15,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/coriander_leaves_fresh.png",
                "category": "fruits-vegetables",
                "unit": "100g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 55
            },
            {
                "name": "Mint Leaves 100g",
                "description": "Cool, refreshing herb for beverages and savory dishes.",
                "price": 15,
                "originalPrice": 20,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/mint_leaves_bunch.png",
                "category": "fruits-vegetables",
                "unit": "100g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 29
            },
            {
                "name": "Mushroom Button 200g",
                "description": "Plump and earthy white button mushrooms.",
                "price": 60,
                "originalPrice": 70,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/button_mushrooms_pack.png",
                "category": "fruits-vegetables",
                "unit": "200g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 33
            },
            {
                "name": "Sweet Potato 1kg",
                "description": "Nutrient-dense root vegetable with a naturally sweet taste.",
                "price": 70,
                "originalPrice": 80,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/sweet_potato_sweet.png",
                "category": "fruits-vegetables",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.3,
                "reviewCount": 12
            },
            {
                "name": "Zucchini Green 500g",
                "description": "Mild tasting squash variety perfect for grilling or zoodles.",
                "price": 55,
                "originalPrice": 65,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/zucchini_green_fresh.png",
                "category": "fruits-vegetables",
                "unit": "500g",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.4,
                "reviewCount": 17
            },
            {
                "name": "Kiwi 3 pcs",
                "description": "Tangy and sweet green kiwi rich in digestive enzymes.",
                "price": 110,
                "originalPrice": 130,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/kiwi_fruit_pack.png",
                "category": "fruits-vegetables",
                "unit": "3pcs",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 21
            },
            {
                "name": "Pomegranate 1kg",
                "description": "Packed with ruby-red, juicy arils bursting with flavor.",
                "price": 190,
                "originalPrice": 220,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/pomegranate_seeds_red.png",
                "category": "fruits-vegetables",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.7,
                "reviewCount": 40
            },
            {
                "name": "Green Apple 1kg",
                "description": "Crisp, tart apple variety excellent for baking and salads.",
                "price": 160,
                "originalPrice": 180,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/green_apple_granny.png",
                "category": "fruits-vegetables",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 26
            },
            {
                "name": "Watermelon 1 pc",
                "description": "Hydrating, sweet summer favorite with crisp red flesh.",
                "price": 80,
                "originalPrice": 100,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/watermelon_whole_sweet.png",
                "category": "fruits-vegetables",
                "unit": "1pc",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.2,
                "reviewCount": 48
            },
            {
                "name": "Papaya 1 pc",
                "description": "Butter-soft tropical fruit loaded with vitamin A.",
                "price": 65,
                "originalPrice": 75,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/papaya_orange_ripe.png",
                "category": "fruits-vegetables",
                "unit": "1pc",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.1,
                "reviewCount": 19
            },
            {
                "name": "Pear 1kg",
                "description": "Sweet, granular-textured fruit with a mild aroma.",
                "price": 140,
                "originalPrice": 160,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/pears_green_sweet.png",
                "category": "fruits-vegetables",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 14
            },
            {
                "name": "Cabbage 1 pc",
                "description": "Leafy green head, standard base for coleslaws and stir-fries.",
                "price": 30,
                "originalPrice": 35,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cabbage_green_whole.png",
                "category": "fruits-vegetables",
                "unit": "1pc",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.0,
                "reviewCount": 22
            },
            {
                "name": "Lady Finger 500g",
                "description": "Tender okra pods perfect for crisp, dry curries.",
                "price": 35,
                "originalPrice": 42,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/okra_ladyfinger_fresh.png",
                "category": "fruits-vegetables",
                "unit": "500g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.2,
                "reviewCount": 30
            },

            // ==========================================
            // DAIRY & EGGS (16 Items)
            // ==========================================
            {
                "name": "Salted Butter 500g",
                "description": "Rich, creamy table butter crafted from pure cow's milk.",
                "price": 265,
                "originalPrice": 275,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/butter_salted_500g.png",
                "category": "dairy-eggs",
                "unit": "500g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.7,
                "reviewCount": 85
            },
            {
                "name": "Unsalted Butter 200g",
                "description": "Premium baking butter without added sodium.",
                "price": 115,
                "originalPrice": 120,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/butter_unsalted_200g.png",
                "category": "dairy-eggs",
                "unit": "200g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 41
            },
            {
                "name": "Greek Yogurt Plain 400g",
                "description": "Thick, strained yogurt rich in protein and probiotics.",
                "price": 140,
                "originalPrice": 160,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/greek_yogurt_plain.png",
                "category": "dairy-eggs",
                "unit": "400g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 53
            },
            {
                "name": "Mozzarella Cheese 200g",
                "description": "Perfect melting cheese for homemade pizzas and lasagnas.",
                "price": 160,
                "originalPrice": 175,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/mozzarella_shred_block.png",
                "category": "dairy-eggs",
                "unit": "200g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 62
            },
            {
                "name": "Heavy Whipping Cream 250ml",
                "description": "Rich dairy cream with a high fat content ideal for whipping.",
                "price": 90,
                "originalPrice": 100,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/whipping_cream_heavy.png",
                "category": "dairy-eggs",
                "unit": "250ml",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 24
            },
            {
                "name": "Fresh Curd 1kg",
                "description": "Creamy, smooth curd made with pasteurized toned milk.",
                "price": 80,
                "originalPrice": 85,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/fresh_curd_dahi_1kg.png",
                "category": "dairy-eggs",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 110
            },
            {
                "name": "Cow Ghee 1L",
                "description": "Pure clarified butter made from traditional churning methods.",
                "price": 650,
                "originalPrice": 700,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cow_ghee_pure_1l.png",
                "category": "dairy-eggs",
                "unit": "1L",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.8,
                "reviewCount": 94
            },
            {
                "name": "Almond Milk Unsweetened 1L",
                "description": "Plant-based, lactose-free milk alternative with a nutty hint.",
                "price": 280,
                "originalPrice": 320,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/almond_milk_vegan.png",
                "category": "dairy-eggs",
                "unit": "1L",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.4,
                "reviewCount": 37
            },
            {
                "name": "Soy Milk Chocolate 1L",
                "description": "Creamy chocolate-flavored soybean milk variant.",
                "price": 160,
                "originalPrice": 180,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/soy_milk_chocolate.png",
                "category": "dairy-eggs",
                "unit": "1L",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.1,
                "reviewCount": 29
            },
            {
                "name": "Sour Cream 200g",
                "description": "Tangy and thick dairy condiment for dips and tacos.",
                "price": 95,
                "originalPrice": 105,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/sour_cream_tub.png",
                "category": "dairy-eggs",
                "unit": "200g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 18
            },
            {
                "name": "Organic Free Range Eggs 6 pcs",
                "description": "Healthy, traceably sourced farm eggs with rich yellow yolks.",
                "price": 90,
                "originalPrice": 100,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/free_range_eggs_6.png",
                "category": "dairy-eggs",
                "unit": "6pcs",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.8,
                "reviewCount": 56
            },
            {
                "name": "Condensed Milk 400g",
                "description": "Sweetened condensed milk ideal for making traditional desserts.",
                "price": 140,
                "originalPrice": 145,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/condensed_milk_can.png",
                "category": "dairy-eggs",
                "unit": "400g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 74
            },
            {
                "name": "Cream Cheese 150g",
                "description": "Soft, spreadable cheese with a mild and slightly tangy flavor.",
                "price": 185,
                "originalPrice": 200,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cream_cheese_spread.png",
                "category": "dairy-eggs",
                "unit": "150g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 26
            },
            {
                "name": "Cheddar Cheese Slices 200g",
                "description": "Convenient individually wrapped savory slices for burgers.",
                "price": 150,
                "originalPrice": 165,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cheddar_slices_pack.png",
                "category": "dairy-eggs",
                "unit": "200g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 49
            },
            {
                "name": "Feta Cheese 200g",
                "description": "Brined, crumbly white cheese with a sharp, salty finish.",
                "price": 240,
                "originalPrice": 270,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/feta_cheese_block.png",
                "category": "dairy-eggs",
                "unit": "200g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 32
            },
            {
                "name": "Buttermilk 500ml",
                "description": "Refreshing and light fermented milk beverage with spices.",
                "price": 30,
                "originalPrice": 35,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/buttermilk_spiced_chaas.png",
                "category": "dairy-eggs",
                "unit": "500ml",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 81
            },

            // ==========================================
            // PANTRY STAPLES (25 Items)
            // ==========================================
            {
                "name": "Extra Virgin Olive Oil 1L",
                "description": "Cold-pressed olive oil perfect for dressings and light cooking.",
                "price": 850,
                "originalPrice": 950,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/olive_oil_evoo_1l.png",
                "category": "pantry-staples",
                "unit": "1L",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.7,
                "reviewCount": 63
            },
            {
                "name": "Sunflower Oil 1L",
                "description": "Light, neutral oil with a high smoke point for daily frying.",
                "price": 160,
                "originalPrice": 180,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/sunflower_cooking_oil.png",
                "category": "pantry-staples",
                "unit": "1L",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.2,
                "reviewCount": 115
            },
            {
                "name": "Pink Himalayan Salt 1kg",
                "description": "Pure unrefined mineral salt mined from ancient deposits.",
                "price": 90,
                "originalPrice": 110,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/pink_salt_himalayan.png",
                "category": "pantry-staples",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.6,
                "reviewCount": 42
            },
            {
                "name": "Organic Turmeric Powder 200g",
                "description": "High curcumin powder with potent anti-inflammatory properties.",
                "price": 65,
                "originalPrice": 75,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/turmeric_powder_organic.png",
                "category": "pantry-staples",
                "unit": "200g",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.8,
                "reviewCount": 51
            },
            {
                "name": "Red Chili Powder 200g",
                "description": "Fiery grounded red chilies to introduce color and heat.",
                "price": 70,
                "originalPrice": 80,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/red_chili_powder.png",
                "category": "pantry-staples",
                "unit": "200g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 38
            },
            {
                "name": "Garam Masala 100g",
                "description": "Aromatic blend of roasted whole spices ground to perfection.",
                "price": 85,
                "originalPrice": 95,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/garam_masala_spice.png",
                "category": "pantry-staples",
                "unit": "100g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.7,
                "reviewCount": 69
            },
            {
                "name": "Toor Dal 1kg",
                "description": "Split pigeon peas, an absolute core component for Indian dals.",
                "price": 175,
                "originalPrice": 190,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/toor_dal_lentils.png",
                "category": "pantry-staples",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 128
            },
            {
                "name": "Moong Dal 1kg",
                "description": "Split yellow mung beans that cook quickly and digest easily.",
                "price": 160,
                "originalPrice": 175,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/moong_dal_yellow.png",
                "category": "pantry-staples",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 92
            },
            {
                "name": "Chana Dal 1kg",
                "description": "Split Bengal gram lentils with a nutty taste and profile.",
                "price": 110,
                "originalPrice": 125,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/chana_dal_pulses.png",
                "category": "pantry-staples",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 74
            },
            {
                "name": "White Chickpeas (Kabuli Chana) 1kg",
                "description": "Premium large chickpeas ideal for authentic chole recipes.",
                "price": 150,
                "originalPrice": 165,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/chickpeas_kabuli_chana.png",
                "category": "pantry-staples",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 81
            },
            {
                "name": "Rajma Kidney Beans 1kg",
                "description": "Premium red kidney beans sourced from the Himalayan foothills.",
                "price": 180,
                "originalPrice": 200,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/rajma_kidney_beans.png",
                "category": "pantry-staples",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 63
            },
            {
                "name": "Rolled Oats 1kg",
                "description": "100% whole grain rolled oats for a wholesome, fibrous breakfast.",
                "price": 195,
                "originalPrice": 220,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/rolled_oats_breakfast.png",
                "category": "pantry-staples",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 114
            },
            {
                "name": "Organic Honey 500g",
                "description": "Pure raw wild forest honey with no added sugar corn syrups.",
                "price": 299,
                "originalPrice": 350,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/honey_wild_organic.png",
                "category": "pantry-staples",
                "unit": "500g",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.7,
                "reviewCount": 88
            },
            {
                "name": "Apple Cider Vinegar 500ml",
                "description": "Raw, unfiltered ACV containing the beneficial 'Mother'.",
                "price": 340,
                "originalPrice": 399,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/apple_cider_vinegar.png",
                "category": "pantry-staples",
                "unit": "500ml",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.4,
                "reviewCount": 45
            },
            {
                "name": "Soy Sauce 500ml",
                "description": "Naturally brewed rich dark soy sauce for Asian culinary bases.",
                "price": 120,
                "originalPrice": 140,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/soy_sauce_dark.png",
                "category": "pantry-staples",
                "unit": "500ml",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 39
            },
            {
                "name": "Tomato Ketchup 1kg",
                "description": "Tangy tomato ketchup prepared from sweet vine-ripened tomatoes.",
                "price": 130,
                "originalPrice": 150,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/tomato_ketchup_bottle.png",
                "category": "pantry-staples",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.2,
                "reviewCount": 152
            },
            {
                "name": "Mayonnaise Eggless 500g",
                "description": "Smooth, rich, and creamy plant-compatible sandwich spread.",
                "price": 150,
                "originalPrice": 170,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/mayonnaise_eggless.png",
                "category": "pantry-staples",
                "unit": "500g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 73
            },
            {
                "name": "Peanut Butter Crunchy 500g",
                "description": "High-protein roasted peanut butter spread packed with crunch.",
                "price": 210,
                "originalPrice": 240,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/peanut_butter_crunchy.png",
                "category": "pantry-staples",
                "unit": "500g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 91
            },
            {
                "name": "Penne Pasta 500g",
                "description": "100% durum wheat semolina pasta shapes that hold sauce beautifully.",
                "price": 95,
                "originalPrice": 110,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/penne_pasta_durum.png",
                "category": "pantry-staples",
                "unit": "500g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 57
            },
            {
                "name": "Chia Seeds 250g",
                "description": "Nutrient dense, fiber-filled omega superseeds for healthy bowls.",
                "price": 180,
                "originalPrice": 220,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/chia_seeds_superfood.png",
                "category": "pantry-staples",
                "unit": "250g",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.6,
                "reviewCount": 33
            },
            {
                "name": "Flax Seeds 250g",
                "description": "Whole raw flaxseeds packed with essential plant fatty acids.",
                "price": 90,
                "originalPrice": 110,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/flax_seeds_omega.png",
                "category": "pantry-staples",
                "unit": "250g",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.3,
                "reviewCount": 21
            },
            {
                "name": "Iodized Salt 1kg",
                "description": "Standard refined table salt fortified with essential iodine.",
                "price": 28,
                "originalPrice": 30,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/table_salt_iodized.png",
                "category": "pantry-staples",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 240
            },
            {
                "name": "Brown Sugar 1kg",
                "description": "Moist, natural brown cane sugar containing molasses notes.",
                "price": 110,
                "originalPrice": 130,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/brown_sugar_cane.png",
                "category": "pantry-staples",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 59
            },
            {
                "name": "Baking Powder 100g",
                "description": "Double-acting leavening agent for uniform cakes and bakes.",
                "price": 45,
                "originalPrice": 50,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/baking_powder_can.png",
                "category": "pantry-staples",
                "unit": "100g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 46
            },
            {
                "name": "Corn Flour 500g",
                "description": "Fine, pure cornstarch powder ideal as a thickening agent.",
                "price": 55,
                "originalPrice": 60,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/corn_flour_powder.png",
                "category": "pantry-staples",
                "unit": "500g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 38
            },

            // ==========================================
            // BEVERAGES (15 Items)
            // ==========================================
            {
                "name": "Green Tea Mint 25 Bags",
                "description": "Refreshing and clean green tea blend mixed with cool mint.",
                "price": 145,
                "originalPrice": 160,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/green_tea_mint_bags.png",
                "category": "beverages",
                "unit": "25bags",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 78
            },
            {
                "name": "Instant Coffee Premium 100g",
                "description": "Richly aromatic, freeze-dried pure coffee bean granules.",
                "price": 290,
                "originalPrice": 320,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/instant_coffee_glass_jar.png",
                "category": "beverages",
                "unit": "100g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 112
            },
            {
                "name": "Pure Coconut Water 200ml",
                "description": "Never-from-concentrate, electrolyte-rich natural hydration.",
                "price": 45,
                "originalPrice": 50,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/coconut_water_tetra.png",
                "category": "beverages",
                "unit": "200ml",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.7,
                "reviewCount": 95
            },
            {
                "name": "Orange Juice 1L",
                "description": "100% pure squeezed orange juice with fresh pulp.",
                "price": 120,
                "originalPrice": 140,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/orange_juice_1l_box.png",
                "category": "beverages",
                "unit": "1L",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 67
            },
            {
                "name": "Apple Juice 1L",
                "description": "Sweet, clear apple juice derived from premium crisp orchard crops.",
                "price": 115,
                "originalPrice": 130,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/apple_juice_pack.png",
                "category": "beverages",
                "unit": "1L",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.2,
                "reviewCount": 43
            },
            {
                "name": "Sparkling Water 500ml",
                "description": "Zero calorie crisp carbonated spring water.",
                "price": 50,
                "originalPrice": 60,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/sparkling_water_bottle.png",
                "category": "beverages",
                "unit": "500ml",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 36
            },
            {
                "name": "Ginger Ale 300ml Can",
                "description": "Bubbly mixer refreshment showcasing crisp ginger spice notes.",
                "price": 60,
                "originalPrice": 65,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/ginger_ale_can.png",
                "category": "beverages",
                "unit": "300ml",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 24
            },
            {
                "name": "Tonic Water 300ml Can",
                "description": "Classic quinine tonic water designed for craft beverages.",
                "price": 60,
                "originalPrice": 65,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/tonic_water_can.png",
                "category": "beverages",
                "unit": "300ml",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.1,
                "reviewCount": 19
            },
            {
                "name": "Assam Black Tea Dust 1kg",
                "description": "Strong, full-bodied black tea leaves ideal for making chai.",
                "price": 320,
                "originalPrice": 360,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/assam_tea_dust_pack.png",
                "category": "beverages",
                "unit": "1kg",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 140
            },
            {
                "name": "Roasted Chicory Coffee 200g",
                "description": "Traditional aromatic blend of fine coffee mixed with chicory.",
                "price": 180,
                "originalPrice": 200,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/chicory_coffee_blend.png",
                "category": "beverages",
                "unit": "200g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 55
            },
            {
                "name": "Tomato Juice Can 300ml",
                "description": "Rich, savory tomato juice lightly seasoned with salt.",
                "price": 75,
                "originalPrice": 85,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/tomato_juice_can.png",
                "category": "beverages",
                "unit": "300ml",
                "stock": 100,
                "isOrganic": false,
                "rating": 3.9,
                "reviewCount": 14
            },
            {
                "name": "Energy Drink Original 250ml",
                "description": "Revitalizing taurine and caffeine carbonated functional energy beverage.",
                "price": 110,
                "originalPrice": 125,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/energy_drink_can.png",
                "category": "beverages",
                "unit": "250ml",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.2,
                "reviewCount": 83
            },
            {
                "name": "Diet Cola 330ml Can",
                "description": "Sugar-free version of your favorite calorie-free sparkling cola.",
                "price": 40,
                "originalPrice": 45,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/diet_cola_can.png",
                "category": "beverages",
                "unit": "330ml",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 102
            },
            {
                "name": "Kombucha Ginger Lemon 300ml",
                "description": "Live probiotic, fermented sparkling tea with real ginger extract.",
                "price": 150,
                "originalPrice": 175,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/kombucha_ginger_bottle.png",
                "category": "beverages",
                "unit": "300ml",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.5,
                "reviewCount": 27
            },
            {
                "name": "Almond Chocolate Shake 200ml",
                "description": "Thick dairy-based sterilized flavored milkshake treat.",
                "price": 40,
                "originalPrice": 45,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/chocolate_shake_bottle.png",
                "category": "beverages",
                "unit": "200ml",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 61
            },

            // ==========================================
            // BAKERY (12 Items)
            // ==========================================
            {
                "name": "Whole Wheat Bread 400g",
                "description": "Freshly baked high-fiber loaf using 100% whole grains.",
                "price": 45,
                "originalPrice": 50,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/whole_wheat_loaf_400g.png",
                "category": "bakery",
                "unit": "400g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 94
            },
            {
                "name": "Garlic Crostini 150g",
                "description": "Twice-baked crispy bread slices infused with garlic butter.",
                "price": 85,
                "originalPrice": 100,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/garlic_crostini_baked.png",
                "category": "bakery",
                "unit": "150g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 26
            },
            {
                "name": "Chocolate Chip Cookies 200g",
                "description": "Crunchy oven-fresh cookies loaded with premium dark chocolate chips.",
                "price": 120,
                "originalPrice": 140,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/chocochip_cookies_box.png",
                "category": "bakery",
                "unit": "200g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 58
            },
            {
                "name": "Multigrain Burger Buns 2 pcs",
                "description": "Soft, sesame-topped buns enriched with healthy grains.",
                "price": 35,
                "originalPrice": 40,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/multigrain_burger_buns.png",
                "category": "bakery",
                "unit": "2pcs",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.2,
                "reviewCount": 34
            },
            {
                "name": "Pita Bread Pack of 5",
                "description": "Soft Mediterranean flatbreads that open into pockets for stuffing.",
                "price": 75,
                "originalPrice": 85,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/pita_bread_pack.png",
                "category": "bakery",
                "unit": "5pcs",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 22
            },
            {
                "name": "Almond Biscotti 150g",
                "description": "Traditional crunchy Italian dipping biscuits containing real nuts.",
                "price": 160,
                "originalPrice": 180,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/almond_biscotti_jar.png",
                "category": "bakery",
                "unit": "150g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.7,
                "reviewCount": 19
            },
            {
                "name": "Plain Bagels 4 pcs",
                "description": "Chewy, dense New York-style boiled and baked plain yeast breads.",
                "price": 110,
                "originalPrice": 120,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/plain_bagels_pack.png",
                "category": "bakery",
                "unit": "4pcs",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 31
            },
            {
                "name": "Fruit Cake Slice 250g",
                "description": "Moist, dense dessert cake studded with candied mixed fruits.",
                "price": 95,
                "originalPrice": 110,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/fruit_cake_loaf.png",
                "category": "bakery",
                "unit": "250g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.1,
                "reviewCount": 42
            },
            {
                "name": "French Baguette 250g",
                "description": "Classic elongated bakery loaf featuring a crisp crust and airy interior.",
                "price": 65,
                "originalPrice": 75,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/french_baguette_crusty.png",
                "category": "bakery",
                "unit": "250g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 50
            },
            {
                "name": "Vanilla Muffins 2 pcs",
                "description": "Soft sponge confectionery muffins filled with pure vanilla aroma.",
                "price": 70,
                "originalPrice": 80,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vanilla_muffins_twin.png",
                "category": "bakery",
                "unit": "2pcs",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 27
            },
            {
                "name": "Cinnamon Rolls 2 pcs",
                "description": "Sweet yeast rolls featuring aromatic cinnamon sugar layers.",
                "price": 130,
                "originalPrice": 150,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cinnamon_rolls_glazed.png",
                "category": "bakery",
                "unit": "2pcs",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.6,
                "reviewCount": 38
            },
            {
                "name": "Pav Buns Pack of 6",
                "description": "Ultra-soft and fluffy pull-apart dinner rolls for native slider meals.",
                "price": 30,
                "originalPrice": 35,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/pav_buns_soft_6.png",
                "category": "bakery",
                "unit": "6pcs",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 118
            },

            // ==========================================
            // SNACKS & PACKAGED FOODS (12 Items)
            // ==========================================
            {
                "name": "Salted Potato Chips 150g",
                "description": "Crispy golden potato wafers dusted uniformly with sea salt.",
                "price": 50,
                "originalPrice": 60,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/potato_chips_salted.png",
                "category": "snacks",
                "unit": "150g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 145
            },
            {
                "name": "Tortilla Nacho Chips 150g",
                "description": "Crunchy corn tortilla triangles seasoned with cheese flavor.",
                "price": 75,
                "originalPrice": 85,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/nacho_chips_cheese.png",
                "category": "snacks",
                "unit": "150g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 89
            },
            {
                "name": "Roasted Cashews 200g",
                "description": "Premium large whole cashews evenly dry-roasted and salted.",
                "price": 260,
                "originalPrice": 290,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/roasted_cashews_salted.png",
                "category": "snacks",
                "unit": "200g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.7,
                "reviewCount": 61
            },
            {
                "name": "California Almonds 200g",
                "description": "Raw, crunchy almonds packed with wholesome vitamin E antioxidants.",
                "price": 240,
                "originalPrice": 260,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/california_almonds_raw.png",
                "category": "snacks",
                "unit": "200g",
                "stock": 100,
                "isOrganic": true,
                "rating": 4.6,
                "reviewCount": 78
            },
            {
                "name": "Dark Chocolate Bar 70% 80g",
                "description": "Rich artisanal single-origin cocoa bean dark tasting bar.",
                "price": 150,
                "originalPrice": 175,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/dark_chocolate_70_bar.png",
                "category": "snacks",
                "unit": "80g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.8,
                "reviewCount": 43
            },
            {
                "name": "Gourmet Popcorn Caramel 125g",
                "description": "Fluffy popped corn kernels thoroughly glazed in sweet buttery caramel.",
                "price": 90,
                "originalPrice": 110,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/caramel_popcorn_tub.png",
                "category": "snacks",
                "unit": "125g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 36
            },
            {
                "name": "Mixed Fruit Jam 500g",
                "description": "Sweet spread composed from a medley of eight delicious orchard fruits.",
                "price": 140,
                "originalPrice": 155,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/mixed_fruit_jam_jar.png",
                "category": "snacks",
                "unit": "500g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.3,
                "reviewCount": 92
            },
            {
                "name": "Corn Flakes Breakfast Cereal 500g",
                "description": "Toasted golden flakes of corn sweetened naturally for morning balance.",
                "price": 170,
                "originalPrice": 190,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/corn_flakes_box.png",
                "category": "snacks",
                "unit": "500g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.1,
                "reviewCount": 115
            },
            {
                "name": "Choco Granola Bar 6 pcs",
                "description": "Chewy, multi-grain morning oat snacks embedded with dark chips.",
                "price": 180,
                "originalPrice": 210,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/granola_bars_choco.png",
                "category": "snacks",
                "unit": "6pcs",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.5,
                "reviewCount": 49
            },
            {
                "name": "Pretzels Twist Original 200g",
                "description": "Traditional oven-baked salted pretzel knots with a crunch finish.",
                "price": 110,
                "originalPrice": 130,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/pretzels_salted_twists.png",
                "category": "snacks",
                "unit": "200g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.2,
                "reviewCount": 23
            },
            {
                "name": "Rice Crackers Cheese 100g",
                "description": "Light and airy baked puffed rice discs dusted with cheese powder.",
                "price": 80,
                "originalPrice": 95,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/rice_crackers_cheese.png",
                "category": "snacks",
                "unit": "100g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.0,
                "reviewCount": 31
            },
            {
                "name": "Wafer Cubes Chocolate 150g",
                "description": "Bite-sized layered crispy wafers filled with chocolate cream inside.",
                "price": 65,
                "originalPrice": 75,
                "image": "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/wafer_cubes_chocolate.png",
                "category": "snacks",
                "unit": "150g",
                "stock": 100,
                "isOrganic": false,
                "rating": 4.4,
                "reviewCount": 54
            }
        ];

        await Product.insertMany(products)
        console.log(`Created ${products.length} products`);
        console.log('Seed completed successfully');
        process.exit(0);
    } catch (err) {
        console.log("Seed error:", err.message);
    } finally {
        await mongoose.disconnect();
    }
}

seedDB();